version: '3.2'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile

    restart: always
    ports:
      - $API_LISTEN_PORT:3001

    volumes:
      - ./srv:/nesorter-api-deps/srv
      - ./.env:/nesorter-api-deps/.env
      - "${HOST_CONTENT_ROOT_DIR_PATH}:${DCKR_CONTENT_ROOT_DIR_PATH}"
